### ISSUE TITLE
Ich habe noch ein paar Bugs gefunden

### ISSUE THREAD

**Issue by Friedjof** [Jean28518/event-management-system#7]
# Bugs & Unstimmigkeiten
- [x] - Error beim Zurücksetzen des Passworts unter /users/5/reset_password/
- [x] - Bug beim Speichern der Änderungen eines Users wird dieser abgemeldet und kann sich nicht mehr anmelden.
- [x] - Weiterleitung zum Login wenn der User nicht eingeloggt ist
- [x] - Was ist wenn es noch keine Vortrage gibt bei send lecture mails?
- [x] - Man sieht einen dünnen Balken zwischen den Buttons und Inputs auf mehreren Seiten
- [x] - Error beim Erstellen eines neuen Vortrags
- [x] - Fehler bei der Anmeldung über /lecture/public/create/entry/ (ich war bereits angemeldet)
- [x] - (/lecture/create/ & /lecture/edit/) Unverständlich wenn keine timeslots vorhanden sind (ganz unten)
- [x] - NOT NULL constraint failed: events_lecture.presentator_id - Fehler abfangen (/lecture/create/)
- [x] - Wird src/event_management_system/events/templates/events/lecture/public_entry.html noch gebraucht?

**Comment by Jean28518** [comment]
Done :) Thanks for reporting!
